trigger:
  branches:
    include:
      - main
      - stage
  paths:
    include:
      - terraform/**

pr:
  branches:
    include:
      - main
  paths:
    include:
      - terraform/**

variables:
  - group: vprofilevariables

stages:
  - stage: Terraform
    displayName: "Apply Terraform Code Changes"
    jobs:
      - job: TerraformJob
        displayName: "Terraform Job"
        pool:
          vmImage: 'ubuntu-latest'
        workspace:
          clean: all
        steps:
          - task: Checkout@1
            displayName: "Checkout source"

          - task: TerraformInstaller@1
            displayName: "Install Terraform"
            inputs:
              terraformVersion: '1.6.3'

          - script: terraform init -backend-config="bucket=$(BUCKET_TF_STATE)"
            displayName: "Terraform Init"
            workingDirectory: ./terraform

          - script: terraform fmt -check
            displayName: "Terraform Format Check"
            workingDirectory: ./terraform

          - script: terraform validate
            displayName: "Terraform Validate"
            workingDirectory: ./terraform

          - script: |
              terraform plan -no-color -input=false -out planfile || echo "##vso[task.setvariable variable=TF_PLAN_FAILED]true"
            displayName: "Terraform Plan"
            workingDirectory: ./terraform

          - script: |
              if [ "$(TF_PLAN_FAILED)" == "true" ]; then exit 1; fi
            displayName: "Fail if Terraform Plan Failed"
